# Numpy

In [2]:
import numpy as np
import pandas as pd

In [8]:
l = ["prince", 2, 3+5j]
type(l)

arr = [2, 5, 66, 43, 3]
x = np.array(arr)
type(x)

np.array(l) #convert into array but the basic operation does not excutable

array(['prince', '2', '(3+5j)'], dtype='<U64')

In [11]:
m =  np.matrix(l) #matrix= 2 dimensional array
m.ndim
x.ndim

1

In [21]:
type(np.array([x])).ndim

np.arange(1, 10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.ones((3, 8)) #made array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.zeros((3, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.random.random((3, 5))

array([[0.90127675, 0.57105251, 0.10285483, 0.24831398, 0.30163639],
       [0.51329087, 0.66155365, 0.45540872, 0.62864798, 0.12971591],
       [0.94840138, 0.7114301 , 0.696222  , 0.08750838, 0.57113511]])

In [23]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [24]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])